name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'functions/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'functions/**'
      - '.github/workflows/ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: functions/package-lock.json
    
    - name: Install dependencies
      run: npm ci
      working-directory: ./functions
    
    - name: Run tests
      run: npm test
      working-directory: ./functions
    
    - name: Run tests with coverage
      if: matrix.node-version == '20.x'
      run: npm run test:coverage
      working-directory: ./functions
    
    - name: Upload coverage reports
      if: matrix.node-version == '20.x'
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: functions/coverage/
    
    - name: Check coverage threshold
      if: matrix.node-version == '20.x'
      run: |
        cd functions
        COVERAGE=$(npx jest --coverage --silent 2>&1 | grep "All files" | awk '{print $10}' | sed 's/%//')
        echo "Test coverage: $COVERAGE%"
        if (( $(echo "$COVERAGE < 80" | bc -l) )); then
          echo "Coverage is below 80% threshold"
          exit 1
        fi
        echo "Coverage meets the 80% threshold ✅"