name: Scraper Tests

on:
  workflow_call:

jobs:
  test:
    name: Docker Scraper Tests
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./scraper
        tags: aki-sta-scraper:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
        load: true
    
    - name: Run tests in Docker
      run: |
        docker run --rm aki-sta-scraper:test python -m pytest tests/ -v
      working-directory: ./scraper
    
    - name: Test scraper execution (dry run)
      run: |
        # テスト環境変数でスクレイパーの起動確認
        docker run --rm --env-file .env.test aki-sta-scraper:test python -m src.entrypoints.cli --help
      working-directory: ./scraper
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: scraper-test-results
        path: scraper/.pytest_cache/
        retention-days: 7